content:
  # Úvodní stránka
  - name: homepage
    label: Úvodní stránka
    type: file
    path: index.md
    fields:
      - name: layout
        type: string
      - name: title
        type: string
      - name: subtitle
        type: string
      - name: body
        type: markdown-body

  # Ostatní stránky
  - name: pages
    label: Ostatní stránky
    type: collection
    path: pages/
    filter:
      include: '*.md'
    fields:
      - name: layout
        type: string
      - name: title
        type: string
      - name: subtitle
        type: string
      - name: body
        type: markdown-body
