# Pages CMS configuration for Jendova-dilna-web

media:
  # Obrázky – používá tvoji složku img/
  - name: images
    label: Obrázky
    input: img

  # Volitelné – pokud chceš upravovat soubory v assets/
  - name: assets
    label: Assets
    input: assets

content:
  # Editace všech markdown stránek v kořeni repozitáře
  - name: pages
    label: Stránky webu
    type: collection
    path: ./
    filename: '{slug}.md'
    filter:
      include: '*.md'
    fields:
      - name: title
        label: Titulek stránky
        type: string

      - name: body
        label: Obsah
        type: rich-text

      - name: slug
        label: Název souboru (slug)
        type: string
        required: true
        description: "Název výsledného .md souboru (např. 'krouzky', 'kontakty')."

settings:
  content:
    merge: true
