content:
  # Ostatní stránky
  - name: pages
    label: Ostatní stránky
    type: collection
    path: pages/
    filter:
      include: '*.md'
    fields:
      - name: layout
        type: string
      - name: title
        type: string
      - name: subtitle
        type: string
      - name: body
        type: markdown-body
